stages:
  - install
  - lint
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  image: node:latest
  script:
    - npm install

run_lint:
  stage: lint
  image: node:latest
  script:
    - npm run lint

build_project:
  stage: build
  image: node:latest
  script:
    - npm run build
